#!/bin/bash

systempath=$1
thispath=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`

rm -rf $1/priv-app/Velvet
rm -rf $1/priv-app/AsusGallery
rm -rf $1/priv-app/SmartReading
rm -rf $1/priv-app/AsusDataTransfer
rm -rf $1/priv-app/DisplayLink
rm -rf $1/app/Photos
rm -rf $1/app/YouTube
rm -rf $1/app/Maps
rm -rf $1/app/Duo
rm -rf $1/app/Drive
rm -rf $1/priv-app/GameModeLiveWallpaper
rm -rf $1/priv-app/YandexBrowser
rm -rf $1/priv-app/YandexApp
rm -rf $1/priv-app/AsusCamera
rm -rf $1/app/Gmail2
rm -rf $1/app/Videos
rm -rf $1/app/GooglePay
rm -rf $1/app/Music2
rm -rf $1/app/Asphalt9
rm -rf $1/priv-app/AsusDataTransfer
rm -rf $1/app/BRApps
rm -rf $1/priv-app/AsusCamera
rm -rf $1/app/Instagram
rm -rf $1/app/FacebookMessenger
rm -rf $1/app/Netflixstubplus
rm -rf $1/app/NetflixActivation
rm -rf $1/priv-app/WeatherTime
rm -rf $1/app/FacebookAppManager
rm -rf $1/app/Facebook
rm -rf $1/priv-app/FacebookInstaller
rm -rf $1/priv-app/FacebookNotificationServices
rm -rf $1/priv-app/MyASUS
rm -rf $1/priv-app/AsusLocalBackup
rm -rf $1/app/AtokIME
rm -rf $1/app/JakartaBaca
rm -rf $1/app/GoogleTTS
rm -rf $1/app/talkback
rm -rf $1/app/mangaDeals
rm -rf $1/priv-app/LogUploader
rm -rf $1/priv-app/ZenUIHelp
rm -rf $1/app/AntHalService
rm -rf $1/app/ROGCNbrowser
rm -rf $1/app/AsusBoost
rm -rf $1/app/ROGCNcloudstorage
rm -rf $1/app/AsusConfigUpdater
rm -rf $1/app/CtsShimPrebuilt
rm -rf $1/app/aptxals
rm -rf $1/app/AsusFMRadio
rm -rf $1/app/ROGCNmobileqq
rm -rf $1/app/ifaa_service
rm -rf $1/app/AsusFMService
rm -rf $1/app/CNAsusAnalytics
rm -rf $1/app/FlipfontMFinanceCN
rm -rf $1/app/NextAppCore
rm -rf $1/app/ROGCNmocmna
rm -rf $1/app/jingdong
rm -rf $1/app/CNAsusEngineerMode
rm -rf $1/app/FlipfontMYingHei
rm -rf $1/app/ROGCNnote
rm -rf $1/app/TGPAServer
rm -rf $1/app/weibo
rm -rf $1/app/AsusHBM
rm -rf $1/app/FlipfontMYuppyCN
rm -rf $1/app/ROGCNqcloud
rm -rf $1/app/CNAsusMusic
rm -rf $1/app/FocusAppListener
rm -rf $1/app/ROGCNtrs
rm -rf $1/app/Traceur
rm -rf $1/app/GameBroadcasterService
rm -rf $1/app/TwinApps
rm -rf $1/app/CNinputmethod
rm -rf $1/app/Protips
rm -rf $1/app/ROGCNweixin
rm -rf $1/app/TwinAppsService
rm -rf $1/app/SMMI_TOOL
rm -rf $1/app/SecureElement
rm -rf $1/priv-app
rm -rf $1/priv-app/AlwaysOn
rm -rf $1/priv-app/AsusVisualMaster
rm -rf $1/priv-app/DisplayLink
rm -rf $1/priv-app/InadvertentTouch
rm -rf $1/priv-app/AsusCalculator
rm -rf $1/priv-app/LocalTransport
rm -rf $1/priv-app/AsusCamera
rm -rf $1/priv-app/CNAsusCallerID
rm -rf $1/priv-app/SmartReading
rm -rf $1/priv-app/LogUploader
rm -rf $1/priv-app/LogUploaderProxy
rm -rf $1/priv-app/StitchImage
rm -rf $1/priv-app/AsusDeskClock
rm -rf $1/priv-app/Tag
rm -rf $1/priv-app/GameBroadcaster
rm -rf $1/priv-app/CNEnhanceServiceManager
rm -rf $1/priv-app/GameModeLiveWallpaper
rm -rf $1/priv-app/NextApp
rm -rf $1/priv-app/AsusGallery
rm -rf $1/priv-app/CNMobileManager
rm -rf $1/priv-app/ONS
rm -rf $1/priv-app/AsusGalleryBurst
rm -rf $1/priv-app/TwinViewLauncher
rm -rf $1/priv-app/AsusLocalBackup
rm -rf $1/priv-app/CNSmartCalendar
rm -rf $1/priv-app/CNSupplementaryDID
rm -rf $1/priv-app/WfdService
rm -rf $1/priv-app/CNWeatherTime
rm -rf $1/priv-app/YodaIpBumperLiveWallpaper
rm -rf $1/priv-app/AsusSoundRecorder
rm -rf $1/priv-app/ROGCNtms
rm -rf $1/priv-app/YodaIpBumperLiveWallpaperSunSX
rm -rf $1/priv-app/AsusSplendid
rm -rf $1/priv-app/ROGGameCenter
rm -rf $1/priv-app/CtsShimPrivPrebuilt
rm -rf $1/priv-app/ScreenRecorder
